<?php
if ($_ENV["EURASIA36_WS_URL"]) {
    const PARAM_WS_HOST = $_ENV["EURASIA36_WS_URL"];
}

if ($_ENV["EURASIA36_WS_USER"]) {
    const PARAM_WS_USER = $_ENV["EURASIA36_WS_USER"];
}

if ($_ENV["EURASIA36_WS_PASSWORD"]) {
    const PARAM_WS_PWD = $_ENV["EURASIA36_WS_PASSWORD"];
}

// const PARAM_JIVOSITE_WIDGET_ID = 'JIVOSITE_WIDGET_ID';

// const PARAM_GA_ID = 'GOOGLE_ANALYTICS_ID';

// const PARAM_YM_ID = 'YANDEX_METRIKA_ID';

// const PARAM_GTM_ID = 'GOOGLE_TAG_MANAGER_ID';

// const PARAM_SHOW_EUBANK_BONUS = 1;
?>