#!/bin/bash

echo "Minifying css"
test -z `which yc 2>/dev/null` && { echo "No yc installed. Skiped"; exit 1; }

find web/css/ -name *.css -exec echo {} minified \;
yc --type css -o '.css$:.css' web/css/*.css

echo "Done"
