#!/bin/bash

export GREEN='\033[0;32m'
export NC='\033[0m' # No Color

echo "`date` Minifying css"
test -z `which yc 2>/dev/null` && { echo "`date` No yc installed. Skiped"; exit 1; }

echo "`date` Building..."
yc --type css -o '.css$:.css' web/css/*.css && {
    find web/css/ -name *.css -exec echo -e "      ${GREEN}write {}${NC}" \;
    echo "`date` Done"
}
