#!/bin/bash

export GREEN='\033[0;32m'
export RED='\033[0;31m'
export NC='\033[0m' # No Color

echo "`date` Rebuilding scss bundles"
test -z `which sass 2>/dev/null` && { echo -e "`date` ${RED}No sass installed. Skiped${NC}"; exit 1; }

echo "`date` Cleanup..."
rm -f web/css/*.css
rm -f web/css/*.css.map

echo "`date` Building..."
sass --update web/scss/:web/css/ && {
    echo "`date` Done"
}
