#!/bin/bash

echo "Rebuilding i18n bundles"
test -z `which msgfmt 2>/dev/null` && { echo "No msgfmt installed. Skipping..."; exit 1; }

recompile_cmd() {
    source=$1
    target=`echo $source | sed -e 's/\.po$/\.mo/'`
    test -f "$target" && action="rewriten" || action="created"
    msgfmt $source -o $target
    echo "$target $action"
}

export -f recompile_cmd

find . -type f -name *.po -exec bash -c 'recompile_cmd "$0"' {} \;

echo "Done"
